#!/bin/sh
#
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push
# @author : Mak Sophea (Extended By Conor Mc Govern
# @version : 1.0
#

# get the path to this script file
DIR=$(dirname "$0")

#if [ -s FILE_NEEDED_TO_RUN_TESTS ]; then
#	## Run Unit Tests
#fi
