#!/bin/sh
#
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push
# @author : Mak Sophea (Extended By Conor Mc Govern)
# @version : 1.0
#

# get the path to this script file
DIR=$(dirname "$0")
COVERAGE_THRESHOLD=50

if [ -s go.mod ]; then
    ## Run Unit Tests
    go test ./...

    if [[ $? != 0 ]]; then
        echo -e "\e[31m> unit tests did not successfully pass\e[0m"
        echo -e "> address unit test failures and attempt to push again"
        exit 1
    fi

    go test $(go list ./... | grep -vw "cmd$" | grep -v internal/services/database_test_utils) -coverprofile cover.out 
    TOTAL_COVERAGE=$(go tool cover -func cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
    if (( $(echo "$TOTAL_COVERAGE $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
        echo "Code coverage is above $COVERAGE_THRESHOLD"
    else
        echo "Code coverage is below threshold. Please add more unit tests."
        echo "Failed"
        exit 1
    fi
fi
