// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://compsoc.ie/terms",
        "contact": {
            "name": "UG CompSoc Admin Team",
            "url": "https://compsoc.ie/support",
            "email": "compsoc@socs.nuigalway.ie"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/ugcompsoc/apid/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Redirect to swagger docs",
                "tags": [
                    "Root"
                ],
                "summary": "Redirect to swagger docs",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect",
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "docs/index.html"
                            }
                        }
                    }
                }
            }
        },
        "/v2": {
            "get": {
                "description": "Responds with 'Root V2' message",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2"
                ],
                "summary": "Get health of API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Message"
                        }
                    }
                }
            }
        },
        "/v2/brew": {
            "get": {
                "description": "Responds with refusal to brew coffee",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2"
                ],
                "summary": "Brew coffee",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Error"
                        }
                    }
                }
            }
        },
        "/v2/healthcheck": {
            "get": {
                "description": "Responds with any service errors",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2"
                ],
                "summary": "Get health of API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Empty"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.Error"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorsArray"
                        }
                    }
                }
            }
        },
        "/v2/ping": {
            "get": {
                "description": "Responds with a pong",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2"
                ],
                "summary": "Ping pong",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.Message"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.Empty": {
            "type": "object"
        },
        "helpers.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "a server error was encountered"
                }
            }
        },
        "helpers.ErrorsArray": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "cannot ping database",
                        "scheduler offline"
                    ]
                }
            }
        },
        "helpers.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "i just wanted to say hi"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "UG CompSoc APId",
	Description:      "Webservices APIv2 for account and IAAS management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
