name: ci-branch
on:
  push:
    branches:    
      - '**'        # matches every branch
      - '!main'     # excludes main

env:
  DOCKERHUB_USERNAME: ugcompsoc
  REPO: ugcompsoc/apid

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get . || true

      - name: Build
        run: go build -v -o bin/ ./cmd/...

      - name: Test with the Go CLI
        run: go test
      
      - name: Git branch and hash vars
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:branch-${{ steps.vars.outputs.branch }}
          labels: |
            maintainer=McGovMan
            maintainer=UGCompSoc
            commit_sha_short=${{ steps.vars.outputs.sha_short }}
