name: delete-branch
on:
  delete:
    branches:    
      - '**'
      - '!main'
      - '!*-prerelease*'

env:
  DOCKERHUB_USERNAME: ugcompsoc
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  REPO: ugcompsoc/apid

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: Git branch and hash vars
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')"

      - name: Run script file
        run: |
          export TAG=branch-$(cat ${{ github.event_path }} | grep -Po '"ref": "*\K[^"]*')
          .github/workflows/delete-branch.sh
        shell: bash
