name: delete-branch
on:
  delete:
    branches:    
      - '**'
      - '!main'
      - '!*-prerelease*'

env:
  DOCKERHUB_USERNAME: ugcompsoc
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  REPO: ugcompsoc/apid

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
          export TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')
          ./github/workflow/delete-branch.sh
        shell: bash