name: 'CI/CD Management Pipeline'

# **What it does**: Manages some of the tasks that can be automated, such as deleting stale docker images.
# **Why we have it**: Automate some of the cumbersome tasks.
# **Who does it impact**: Branch docker images in DockerHub.

on:
  delete:
    branches:    
      - '**'
  release:
    types:
      - deleted

env:
  DOCKERHUB_USERNAME: ugcompsoc
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  REPO: ugcompsoc/apid

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: Git branch and hash vars
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')"

      - name: Run script file
        run: |
          export TAG=$(cat ${{ github.event_path }} | grep -Po '"ref": "*\K[^"]*')
          .github/workflow_scripts/delete-branch.sh
        shell: bash
