name: On branch push, update the container running in DEV

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  call-unit-tests:
    uses: ./.github/workflows/reusable_unit_tests.yml
  get-branch-name:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      branch_name: ${{ steps.branch_name.outputs.branch }}
    steps:
      - name: Git branch name
        id: branch_name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')"
  call-build-publish:
    needs: [call-unit-tests, get-branch-name]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        ugcompsoc/apid:${{ needs.get-branch-name.outputs.branch_name }}
        ugcompsoc/apid:latest
    secrets: inherit
  call-deployment:
    needs: [call-build-publish, get-branch-name]
    uses: ./.github/workflows/reusable_deployment.yml
    with:
      tag_name: ${{ needs.get-branch-name.outputs.branch_name }}
      environment: DEV
    secrets: inherit
  call-api-tests:
    needs: [call-deployment, get-branch-name]
    uses: ./.github/workflows/reusable_api_tests.yml
    with:
      tag_name: ${{ needs.get-branch-name.outputs.branch_name }}
      environment: DEV
