name: On branch deletion, remove the container running in the environment

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Git branch name
        id: branch_name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')"
  call-remove:
    needs: [get-branch-name]
    uses: ./.github/workflows/reusable_remove.yml@${{ needs.get-branch-name.outputs.branch_name }}
    with:
      image_name: ${{ needs.get-branch-name.outputs.branch_name }}
