name: On main push, update the container running in TEST

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  call-unit-tests:
    uses: ./.github/workflows/reusable_unit_tests.yml
  call-verify-swagger:
    uses: ./.github/workflows/reusable_verify_swagger.yml
  get-version:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "/(BREAKING CHANGE:|!)/"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"
  call-build-publish:
    needs: [call-unit-tests, get-version]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        ugcompsoc/apid:${{ needs.get-version.outputs.version }}
        ugcompsoc/apid:unstable
        ugcompsoc/apid:latest
    secrets: inherit
  call-remove:
    needs: [call-unit-tests]
    uses: ./.github/workflows/reusable_remove_deployment.yml
    with:
      tag_name: prerelease
    secrets: inherit
  call-deployment:
    needs: [call-build-publish, get-version]
    uses: ./.github/workflows/reusable_deployment.yml
    with:
      tag_name: ${{ needs.get-version.outputs.version }}
      environment: TEST
    secrets: inherit
  call-api-tests:
    needs: [call-deployment, get-version]
    uses: ./.github/workflows/reusable_api_tests.yml
    with:
      tag_name: ${{ needs.get-version.outputs.version }}
      environment: TEST
