name: On main push, update the container running in TEST

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  call-test:
    uses: ./.github/workflows/reusable_test.yml
  get-version:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "/(BREAKING CHANGE:|!)/"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"
  call-build-publish:
    needs: [call-test, get-version]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        ugcompsoc/apid:${{ needs.get-version.outputs.version }}
        ugcompsoc/apid:latest
    secrets: inherit
  call-deployment:
    needs: [call-build-publish, get-version]
    uses: ./.github/workflows/reusable_deployment.yml
    with:
      tag_name: ${{ needs.get-version.outputs.version }}
      environment: TEST
    secrets: inherit
