name: On tag creation, update the container running in PROD

on:
  push:
    tags:
      - 'v2.*'

jobs:
  call-test:
    uses: ./.github/workflows/reusable_test.yml
  call-build-publish:
    needs: [call-test]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        ugcompsoc/apid:${{ github.event.ref }}
        ugcompsoc/apid:stable
        ugcompsoc/apid:latest
    secrets: inherit
  call-deployment:
    needs: [call-build-publish]
    uses: ./.github/workflows/reusable_deployment.yml
    with:
      tag_name: ${{ github.event.ref }}
      environment: PROD
    secrets: inherit
