name: On tag creation, update the container running in PROD

on:
  push:
    tags:
      - 'v2.*'

jobs:
  call-unit-tests:
    uses: ./.github/workflows/reusable_unit_tests.yml
  get-tag-name:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Get tag name
        id: tag
        shell: bash
        run: |
          GITHUB_REF=${{ github.event.ref }}
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//} || true
  call-build-publish:
    needs: [call-unit-tests, get-tag-name]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        ugcompsoc/apid:${{ needs.get-tag-name.outputs.tag }}
        ugcompsoc/apid:stable
        ugcompsoc/apid:latest
    secrets: inherit
  call-remove:
    needs: [call-unit-tests, get-tag-name]
    uses: ./.github/workflows/reusable_remove_deployment.yml
    with:
      tag_name: compsoc_apid_v2.
    secrets: inherit
  call-deployment:
    needs: [call-build-publish, get-tag-name]
    uses: ./.github/workflows/reusable_deployment.yml
    with:
      tag_name: ${{ needs.get-tag-name.outputs.tag }}
      environment: PROD
    secrets: inherit
