name: Deploy to environment

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Provide the tag you wish to deploy"
        type: string
        required: true
      environment:
        type: string
        description: "Provide the environment you would like the image to be deployed on, e.g. DEV, TEST or PROD"
        required: true
        default: DEV
    secrets:
      SSH_HOST:
        description: "Provide the FQDN or IP address of the server to deploy on"
        required: true
      SSH_USERNAME:
        description: "Provide the username to login with"
        required: true
      SSH_SECRET:
        description: "Provide the private SSH key to login with"
        required: true
      SSH_PORT:
        description: "Provide the SSH port"
        required: true

jobs:
  get-url:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      url: ${{ steps.url.outputs.url }}
    steps:
      - name: Get API URL
        id: url
        shell: bash
        run: |
          echo "##[set-output name=url;]$(echo ${{ inputs.tag_name}}.dev.apid.testbox.compsoc.ie)" || true
          [ ${{ inputs.environment }} = "TEST" ] && echo "##[set-output name=url;]$(echo dev.apid.testbox.compsoc.ie)" || true
          [ ${{ inputs.environment }} = "PROD" ] && echo "##[set-output name=url;]$(echo apid.testbox.compsoc.ie)" || true
  deployment:
    needs: [get-url]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker run \
              --name compsoc_apid_${{ inputs.tag_name }} \
              --network=transit-public \
              --label traefik.http.routers.ugcompsoc_apid_${{ inputs.tag_name }}.rule=Host\(\`${{ needs.get-url.outputs.url }}\`\) \
              --label traefik.http.routers.ugcompsoc_apid_${{ inputs.tag_name }}.entrypoints=websecure \
              --label traefik.http.routers.ugcompsoc_apid_${{ inputs.tag_name }}.tls=true \
              --label traefik.http.routers.ugcompsoc_apid_${{ inputs.tag_name }}.tls.certresolver=myresolver \
              --label traefik.docker.network=transit-public \
              --restart unless-stopped \
              ugcompsoc/apid:${{ inputs.tag_name }}