on:
  workflow_call:
    inputs:
      tag_name:
        description: "Provide all image tag name you wish to remove the deployment for"
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_USERNAME:
        description: "Provide the username of the account that has access to publish to the registry"
        required: true
      DOCKER_REGISTRY_PASSWORD:
        description: "Provide the password for the account that has access to publish to the registry"
        required: true

jobs:
  remove-image:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Login and delete tag
        id: branch_name
        shell: bash
        run: |
          REPO="ugcompsoc/apid"

          echo "> Requesting token from https://hub.docker.com/v2/users/login/"
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKER_REGISTRY_USERNAME }}'", "password": "'${{ secrets.DOCKER_REGISTRY_PASSWORD }}'"}' https://hub.docker.com/v2/users/login/ | grep -Po '"token":"*\K[^"]*')

          echo "> Get all images that contain tag_name"
          curl "https://hub.docker.com/v2/namespaces/ugcompsoc/repositories/apid/tags?page_size=100" | grep -o '"name": *"[^"]*' | grep -o '[^"]*$' | sed '/${{ inputs.tag_name }}/!d' >> tags.txt
          while IFS="" read -r p || [ -n "$tag" ]
          do
            echo "> Requesting deletion of ${tag} from $REPO -> https://hub.docker.com/v2/repositories/${REPO}/tags/${tag}/"
            curl -i -X DELETE \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $TOKEN" \
              "https://hub.docker.com/v2/repositories/${REPO}/tags/${tag}/"
          done < tags.txt
