on:
  workflow_call:
    inputs:
      tag_name:
        description: "Provide the image name you wish to get the url for"
        required: true
        type: string
      environment:
        type: string
        description: "Provide the environment you would like the image to be deployed on, e.g. DEV, TEST or PROD"
        required: true
        default: DEV
    outputs:
      url:
        description: "The first job output"
        value: ${{ jobs.get-url.outputs.url }}

jobs:
  get-url:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      url: ${{ steps.url.outputs.url }}
    steps:
      - name: Get API URL
        id: url
        shell: bash
        run: |
          TAG_NAME=${{ inputs.tag_name }}
          TAG_NAME=$(echo "$TAG_NAME" | sed -r 's/[._/]+/-/g' | sed 's/-$//')
          echo "##[set-output name=url;]$(echo ${TAG_NAME:0:32}.dev.apid.testbox.compsoc.ie)" || true
          [ ${{ inputs.environment }} = "TEST" ] && echo "##[set-output name=url;]$(echo dev.apid.testbox.compsoc.ie)" || true
          [ ${{ inputs.environment }} = "PROD" ] && echo "##[set-output name=url;]$(echo apid.testbox.compsoc.ie)" || true