name: Run tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get . || true

      - name: Test with the Go CLI
        run: go test ./...
