name: Create and publish docker images

on:
  workflow_call:
    inputs:
      image_names:
        description: "Provide all image names that you wish to publish the image under"
        required: false
        type: string
        default: |
          ugcompsoc/apid:latest
          ugcompsoc/apid:dummy_tag
    secrets:
      docker_registry_username:
        description: "Provide the username of the account that has access to publish to the registry"
        required: true
      docker_registry_password:
        description: "Provide the password for the account that has access to publish to the registry"
        required: true

jobs:
  build-push-image:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_registry_username }}
          password: ${{ secrets.docker_registry_password }}

      - name: Build and push branch
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ inputs.image_names }}
