name: Run Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get . || true

      - name: Test with the Go CLI
        run: go test ./...
      
      - name: Code Coverage
        env:
          COVERAGE_THRESHOLD: 75
        run: |
          go test $(go list ./... | grep -v cmd) -coverprofile cover.out 
          TOTAL_COVERAGE=$(go tool cover -func cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
          if (( $(echo "$TOTAL_COVERAGE $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
            echo "Code coverage is above $COVERAGE_THRESHOLD"
          else
            echo "Code coverage is below threshold. Please add more unit tests."
            echo "Failed"
            exit 1
          fi
