name: Run API Tests

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Provide the tag you wish to deploy"
        type: string
        required: true
      environment:
        type: string
        description: "Provide the environment you would like the image to be deployed on, e.g. DEV, TEST or PROD"
        required: true
        default: DEV

jobs:
  get-url:
    uses: ./.github/workflows/reusable_get_url.yml
    with:
      tag_name: ${{ inputs.tag_name }}
      environment: ${{ inputs.environment }}
  api-tests:
    needs: [get-url]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      - name: Run Venom Tests
        shell: bash
        run: |
          curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o /usr/local/bin/venom
          chmod +x /usr/local/bin/venom
          echo "url: 'https://${{ needs.get-url.outputs.url }}'" > venom_vars_tmp.yml
          venom run venom/*.yml --var-from-file venom_vars_tmp.yml --output-dir test_results