name: Run API Tests

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Provide the tag you wish to deploy"
        type: string
        required: true
      environment:
        type: string
        description: "Provide the environment you would like the image to be deployed on, e.g. DEV, TEST or PROD"
        required: true
        default: DEV

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run Venom Tests
        shell: bash
        run: |
          curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o /usr/local/bin/venom
          chmod +x /usr/local/bin/venom
          venom run **/*_venom.yml --var-from-file venom_vars.yml --output-dir test_results