name: 'Test API On Push Pipeline'

# **What it does**: Sets up the go application, and runs unit tests.
# **Why we have it**: To allow for tested code to be deployed to staging and production environments.
# **Who does it impact**: Nothing. This workflow is used as a skeleton for other workflows.

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

env:
  DOCKERHUB_USERNAME: ugcompsoc
  REPO: ugcompsoc/apid

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      
      - name: Install dependencies
        run: go get . || true

      - name: Test with the Go CLI
        run: go test ./...
